# docker-compose.yml
# Определение сервисов (контейнеров) которые будут запущены
services:
  # Сервис приложения (backend)
  app:
    # Сборка образа из текущей директории
    build:
      context: .
    # Имя и тег собранного образа
    image: eng-app:latest
    # Имя контейнера после запуска
    container_name: eng_app
    # Политика перезапуска: всегда перезапускать при падении
    restart: always
    # Зависимости - этот сервис зависит от сервиса db
    depends_on:
      - db
    # Файл с переменными окружения
    env_file:
      - ./.env.docker
    # Команда которая выполнится при запуске контейнера:
    # 1. Применяем миграции Alembic
    # 2. Запускаем сервер FastAPI через Uvicorn
    command: >
      sh -c "alembic upgrade head &&
      python -m app.core.seed.run &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"


    # Проброс портов: хост:контейнер
    ports:
      - "8000:8000"  # Внешний порт 8000 → внутренний 8000 контейнера
    # Добавьте том для загрузок
#    volumes:
#      - app_uploads_data:/app/uploads # Монтируем именованный том в директорию
#      - ./:/app  # Монтируем текущую директорию в /app в контейнере


  # Сервис базы данных PostgreSQL
  db:
    # Используем официальный образ PostgreSQL 15 версии
    image: postgres:15
    # Имя контейнера после запуска
    container_name: eng_db
    # Монтируем том для хранения данных БД
    volumes:
      - postgres_data_eng:/var/lib/postgresql/data/
    # Файл с переменными окружения (логин, пароль и т.д.)
    env_file:
      - ./.env.docker

# Определение томов для хранения данных
volumes:
  postgres_data_eng:
    # Используются настройки по умолчанию
  app_uploads_data: # Объявление тома для загрузок
