"""changes

Revision ID: e44fbcf04c76
Revises: 0d8cff0a4654
Create Date: 2026-01-09 11:30:33.730840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44fbcf04c76'
down_revision: Union[str, Sequence[str], None] = '0d8cff0a4654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_word_category', 'word_categories', ['word_id', 'category_id'])
    op.drop_column('word_categories', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_categories', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('uq_word_category', 'word_categories', type_='unique')
    # ### end Alembic commands ###
