"""add favorite_words

Revision ID: cc029b1ac92b
Revises: 7e6c48708e3f
Create Date: 2026-01-10 12:55:51.981104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc029b1ac92b'
down_revision: Union[str, Sequence[str], None] = '7e6c48708e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_words',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'word_id')
    )
    # op.create_unique_constraint('uq_word_category', 'word_categories', ['word_id', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_word_category', 'word_categories', type_='unique')
    op.drop_table('favorite_words')
    # ### end Alembic commands ###
