"""add image_url

Revision ID: 5be43d8783c1
Revises: 967edba001e4
Create Date: 2026-03-05 13:12:42.102675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be43d8783c1'
down_revision: Union[str, Sequence[str], None] = '967edba001e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('image_url', sa.String(length=500), nullable=True, comment='URL изображения слова'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'image_url')
    # ### end Alembic commands ###
